---
# COUNTIES
- name: "counties"
  as_of: "2020-01-01"
  geography_type: "county"
  epsg: 4269
  published_on: "2021-02-02"
  source: "2020 TIGER/Line Shapefiles, U.S. Census Bureau"
  files:
    counties: "census/counties/tl_2020_us_county.zip"
    county_fips: "census/counties/fips.csv"

# DISTRESSED COMMUNITIES
- name: "distressed communities"
  as_of: "2022-01-01"
  geography_type: "distressed"
  epsg: 4269
  published_on: null
  source: "Distressed Communities Index (DCI), Economic Innovation Group"
  files:
    distress_scores: "bonus/distressed/DCI-2016-2020-Academic-Non-profit-Government-Scores-Only.xlsx"
    zctas: "census/zip_codes/tl_2020_us_zcta520.zip"
    
# ENERGY COMMUNITIES - COAL
- name: "energy communities - coal"
  as_of: "2023-01-01"
  geography_type: "energy"
  epsg: 4269
  published_on: "2023-06-15"
  source: "Interagency Working Group on Coal & Power Plant Communities & Economic Revitalization, National Energy Technology Lab, Department of Energy"
  files:
    coal_communities: "/bonus/energy/ira_coal_closure_energy_comm_2023v2.zip!IRA_Coal_Closure_Energy_Comm_2023v2/Coal_Closure_Energy_Communities_SHP_2023v2"

# ENERGY COMMUNITIES - FOSSIL FUELS
- name: "energy communities - fossil fuels"
  as_of: "2023-01-01"
  geography_type: "energy"
  epsg: 4269
  published_on: "2023-06-15"
  source: "Interagency Working Group on Coal & Power Plant Communities & Economic Revitalization, National Energy Technology Lab, Department of Energy"
  files:
    fossil_fuel_communities: "bonus/energy/msa_nmsa_fee_ec_status_2023v2.zip!MSA_NMSA_FEE_EC_Status_2023v2/MSA_NMSA_FEE_EC_Status_SHP_2023v2"

# JUSTICE40 COMMUNITIES
- name: "justice40 communities"
  as_of: "2019-01-01"
  geography_type: "justice40"
  epsg: 4326
  published_on: "2022-11-22"
  source: "Climate and Economic Justice Screening Tool v.1.0, Council on Environmental Quality, Executive Office of the President"
  files:
    justice40_communities: "bonus/justice40/usa.zip"

# LOW-INCOME COMMUNITIES
- name: "low-income communities"
  as_of: "2020-01-01"
  geography_type: low-income
  epsg: 4269
  published_on: "2023-09-01"
  source: "NMTC Program, Department of the Treasury"
  files:
    county_fips: "census/counties/fips.csv"
    low_income_2011_2015: "bonus/low_income/nmtc-2011-2015-lic-nov2-2017-4pm.xlsx"
    low_income_2016_2020: "bonus/low_income/NMTC_2016-2020_ACS_LIC_Sept1_2023.xlsb"
    state_fips: "census/states/fips.csv"
    tracts_2010: "census/tracts/tl_2010_[6-7]*_tract10.zip"
    tracts_2020: "census/tracts/tl_2020_**_tract.zip"

# MUNICIPALITIES
- name: "municipalities"
  as_of: "2020-01-01"
  geography_type: "municipality"
  epsg: 4269
  published_on: "2021-02-02"
  source: "2020 TIGER/Line Shapefiles, U.S. Census Bureau"
  files:
    county_fips: "census/counties/fips.csv"
    county_subdivisions: "census/county_subdivisions/**.zip"
    state_fips: "census/states/fips.csv"

# MUNICIPAL UTILITIES
- name: "municipal utilities"
  as_of: "2022-12-09"
  geography_type: "municipal utility"
  epsg: 4326
  published_on: null
  source: "Geospatial Management Office, U.S. Department of Homeland Security"
  files:
    corrected_names: "bonus/retail/municipal_utility_name_matches.csv"
    utilities: "bonus/retail/Electric_Retail_Service_Territories.zip"

# RURAL COOPERATIVES
- name: "rural cooperatives"
  as_of: "2022-12-09"
  geography_type: "rural cooperative"
  epsg: 4326
  published_on: null
  source: "Geospatial Management Office, U.S. Department of Homeland Security"
  files:
    utilities: "bonus/retail/Electric_Retail_Service_Territories.zip"

# STATES
- name: "states"
  as_of: "2020-01-01"
  geography_type: "state"
  epsg: 4269
  published_on: "2021-02-02"
  source: "2020 TIGER/Line Shapefiles, U.S. Census Bureau"
  files:
    states: "census/states/tl_2020_us_state.zip"
...