version: '3.4'
services:

  # POSTGIS
  climate-cabinet-postgis:
    image: postgis/postgis:13-3.3
    environment:
      - POSTGRES_PASSWORD=postgres
    # volumes:
        # - ./pgdata:/var/lib/postgresql/data

  # PIPELINE
  climate-cabinet-pipeline:      
    environment:
      - DJANGO_SECRET_KEY=local
      - ENV=DEV
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=climate-cabinet-postgis
    build:
      args:
        ENV: DEV
      context: pipeline
    command: ./cr-entry.sh
    volumes:
      - ./pipeline:/pipeline
      - ./data:/data
    depends_on:
      - climate-cabinet-postgis
      - climate-cabinet-pgadmin

  # PGADMIN DATABASE GUI
  climate-cabinet-pgadmin:
    depends_on:
      - climate-cabinet-postgis
    environment:
      - COMPOSE_HTTP_TIMEOUT=300
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com 
      - PGADMIN_DEFAULT_PASSWORD=p@sssw0rd!123
      - PGADMIN_LISTEN_PORT=443
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    image: dpage/pgadmin4
    ports:
      - "443:443"
    volumes:
      - ./server.local.json:/pgadmin4/servers.json
