version: "3.4"

services:

  # POSTGIS
  postgis:
    image: postgis/postgis:13-3.3
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # PIPELINE - DEVELOPMENT SERVER
  pipeline-interactive:
    command:
      - "bash"
      - "setup.sh"
      - "--run-server"
    restart: "no"
    env_file:
      - ./pipeline/.env.dev
    build:
      context: pipeline
    ports:
      - "8080:8080"
    volumes:
      - ./pipeline:/pipeline
      - ./data:/data
    depends_on:
      - postgis
      - pgadmin
    profiles:
      - pipeline-interactive

  # PIPELINE - FULL EXECUTION
  pipeline-execution:
    extends:
      service: pipeline-interactive
    command:
      - "bash"
      - "setup.sh"
      - "--migrate"
      - "--clean-data"
      - "--load-geos"
      - "--load-associations"
      - "--sync-mapbox"
    profiles:
      - pipeline-execution

  # PGADMIN DATABASE GUI
  pgadmin:
    depends_on:
      - postgis
    image: dpage/pgadmin4
    platform: ${DOCKER_PLATFORM}
    environment:
      - COMPOSE_HTTP_TIMEOUT=300
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=p@sssw0rd!123
      - PGADMIN_LISTEN_PORT=443
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - "443:443"
    volumes:
      - ./server.local.json:/pgadmin4/servers.json
      - ./data:/data

  # DASHBOARD
  dashboard:
    build:
      context: dashboard
    depends_on:
      - postgis
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./dashboard:/app
      - /app/node_modules
      - /app/.next
    profiles:
      - dashboard
