global:

base:
  geography_type:
    active: False
    filename: clean/csv/geography_type.csv
    filetype: csv
    row_transform: tax_credit.record_transforms:load_geography_type_row
    model: tax_credit.models:GeographyType
    file_format: csv
    file_field_required:
    - Id
    - Name
    db_field_unique:
    - id
    db_field_update:
    - name
  program:
    active: False
    filename: clean/csv/program.csv
    file_format: csv
    row_transform: tax_credit.record_transforms:load_program_type_row
    model: tax_credit.models:Program
    file_field_required:
    - Id
    - Program
    - Agency
    - Description
    - Base_benefit
    db_field_unique:
    - id
    db_field_update:
    - name
    - agency
    - description
    - base_benefit
  block_group_2010:
    active: False
    filename: raw/census/block_groups/CenPop2010_Mean_BG.txt
    delimiter: ","
    file_format: csv
    row_transform: tax_credit.record_transforms:load_census_block_row_2010
    model: tax_credit.models:CensusBlockGroup
    db_field_unique:
    - id
    file_field_required:
    - STATEFP
    - COUNTYFP
    - TRACTCE
    - BLKGRPCE
    - POPULATION
    - LATITUDE
    - LONGITUDE
    db_field_update:
    - population
  block_group_2020:
    active: False
    delimiter: ","
    filename: raw/census/block_groups/CenPop2020_Mean_BG.txt
    file_format: csv
    row_transform: tax_credit.record_transforms:load_census_block_row_2020
    model: tax_credit.models:CensusBlockGroup
    db_field_unique:
    - id
    file_field_required:
    - STATEFP
    - COUNTYFP
    - TRACTCE
    - BLKGRPCE
    - POPULATION
    - LATITUDE
    - LONGITUDE
    db_field_update:
    - population

dependent:
  geography_to_program:
    active: False
    filename: clean/csv/geography_type_program.csv
    filetype: csv
    row_transform: tax_credit.record_transforms:load_geography_program_match_row
    model: tax_credit.models:GeographyTypeProgram
    file_format: csv
    file_field_required:
    - Id
    - Geography_Type
    - Program
    - Abount_Description
    db_field_unique:
    - id
    db_field_update:
    - geography_type
    - program
    - amount_description
  counties:
    active: False
    filename: clean/geoparquet/counties.geoparquet
    filetype: parquet
    row_transform: tax_credit.record_transforms:load_geography_dataset_row
    model: tax_credit.models:Geography
    file_format: parquet
    required_model:
    - tax_credit.models:GeographyType
    db_field_unique:
    - name
    - geography_type
    - fips
    file_field_required:
    - fips
    - geography_type
    - as_of
    - published_on
    - source
    - geometry
    db_field_update:
    - fips
    - geography_type
    - as_of
    - published_on
    - source
    - geometry
  distressed_communities:
    active: False
    filename: clean/geoparquet/distressed_communities.geoparquet
    filetype: parquet
    row_transform: tax_credit.record_transforms:load_geography_dataset_row
    model: tax_credit.models:Geography
    file_format: parquet
    required_model:
    - tax_credit.models:GeographyType
    db_field_unique:
    - name
    - geography_type
    - fips
    file_field_required:
    - fips
    - geography_type
    - as_of
    - published_on
    - source
    - geometry
    db_field_update:
    - fips
    - geography_type
    - as_of
    - published_on
    - source
    - geometry
  coal_communities:
    active: False
    filename: clean/geoparquet/energy_communities___coal.geoparquet
    filetype: parquet
    row_transform: tax_credit.record_transforms:load_geography_dataset_row
    model: tax_credit.models:Geography
    file_format: parquet
    required_model:
    - tax_credit.models:GeographyType
    db_field_unique:
    - name
    - geography_type
    - fips
    file_field_required:
    - fips
    - geography_type
    - as_of
    - published_on
    - source
    - geometry
    db_field_update:
    - fips
    - geography_type
    - as_of
    - published_on
    - source
    - geometry
  fossil_fuel_communities:
    active: False
    filename: clean/geoparquet/energy_communities___fossil_fuels.geoparquet
    filetype: parquet
    row_transform: tax_credit.record_transforms:load_geography_dataset_row
    model: tax_credit.models:Geography
    file_format: parquet
    required_model:
    - tax_credit.models:GeographyType
    db_field_unique:
    - name
    - geography_type
    - fips
    file_field_required:
    - fips
    - geography_type
    - as_of
    - published_on
    - source
    - geometry
    db_field_update:
    - fips
    - geography_type
    - as_of
    - published_on
    - source
    - geometry
  justice40:
    active: False
    filename: clean/geoparquet/justice40_communities.geoparquet
    filetype: parquet
    row_transform: tax_credit.record_transforms:load_geography_dataset_row
    model: tax_credit.models:Geography
    file_format: parquet
    required_model:
    - tax_credit.models:GeographyType
    db_field_unique:
    - name
    - geography_type
    - fips
    file_field_required:
    - fips
    - geography_type
    - as_of
    - published_on
    - source
    - geometry
    db_field_update:
    - fips
    - geography_type
    - as_of
    - published_on
    - source
    - geometry
  low_income:
    active: False
    filename: clean/geoparquet/low_income_communities.geoparquet
    filetype: parquet
    row_transform: tax_credit.record_transforms:load_geography_dataset_row
    model: tax_credit.models:Geography
    file_format: parquet
    required_model:
    - tax_credit.models:GeographyType
    db_field_unique:
    - name
    - geography_type
    - fips
    file_field_required:
    - fips
    - geography_type
    - as_of
    - published_on
    - source
    - geometry
    db_field_update:
    - fips
    - geography_type
    - as_of
    - published_on
    - source
    - geometry
  municiapl_utilities:
    active: False
    filename: clean/geoparquet/municipal_utilities.geoparquet
    filetype: parquet
    row_transform: tax_credit.record_transforms:load_geography_dataset_row
    model: tax_credit.models:Geography
    file_format: parquet
    required_model:
    - tax_credit.models:GeographyType
    db_field_unique:
    - name
    - fips
    - geography_type
    file_field_required:
    - fips
    - geography_type
    - as_of
    - published_on
    - source
    - geometry
    db_field_update:
    - fips
    - geography_type
    - as_of
    - published_on
    - source
    - geometry
  municipalities:
    active: False
    filename: clean/geoparquet/municipalities.geoparquet
    filetype: parquet
    row_transform: tax_credit.record_transforms:load_geography_dataset_row
    model: tax_credit.models:Geography
    file_format: parquet
    required_model:
    - tax_credit.models:GeographyType
    db_field_unique:
    - name
    - geography_type
    - fips
    file_field_required:
    - fips
    - geography_type
    - as_of
    - published_on
    - source
    - geometry
    db_field_update:
    - fips
    - geography_type
    - as_of
    - published_on
    - source
    - geometry
  rural_coops:
    active: False
    filename: clean/geoparquet/rural_cooperatives.geoparquet
    filetype: parquet
    row_transform: tax_credit.record_transforms:load_geography_dataset_row
    model: tax_credit.models:Geography
    file_format: parquet
    required_model:
    - tax_credit.models:GeographyType
    db_field_unique:
    - name
    - geography_type
    - fips
    file_field_required:
    - fips
    - geography_type
    - as_of
    - published_on
    - source
    - geometry
    db_field_update:
    - fips
    - geography_type
    - as_of
    - published_on
    - source
    - geometry
  state:
    active: False
    filename: clean/geoparquet/states.geoparquet
    filetype: parquet
    row_transform: tax_credit.record_transforms:load_geography_dataset_row
    model: tax_credit.models:Geography
    file_format: parquet
    required_model:
    - tax_credit.models:GeographyType
    db_field_unique:
    - name
    - geography_type
    - fips
    file_field_required:
    - fips
    - geography_type
    - as_of
    - published_on
    - source
    - geometry
    db_field_update:
    - fips
    - geography_type
    - as_of
    - published_on
    - source
    - geometry

assoc:
  state_to_distressed:
    active: False
    model: tax_credit.models:TargetBonusAssoc
    target: state
    bonus: distressed
    assoc_strategy: overlap
    db_field_unique:
    - target_geography
    - bonus_geography
    db_field_update:
    - target_geography_type
    - bonus_geography_type
  state_to_energy:
    active: False
    model: tax_credit.models:TargetBonusAssoc
    target: state
    bonus: energy
    assoc_strategy: fips_state
    db_field_unique:
    - target_geography
    - bonus_geography
    db_field_update:
    - target_geography_type
    - bonus_geography_type
  state_to_j40:
    active: False
    model: tax_credit.models:TargetBonusAssoc
    target: state
    bonus: justice40
    assoc_strategy: fips_state
    db_field_unique:
    - target_geography
    - bonus_geography
    db_field_update:
    - target_geography_type
    - bonus_geography_type
  state_to_low_income:
    active: False
    model: tax_credit.models:TargetBonusAssoc
    target: state
    bonus: low_income
    assoc_strategy: fips_state
    db_field_unique:
    - target_geography
    - bonus_geography
    db_field_update:
    - target_geography_type
    - bonus_geography_type

  county_to_distressed:
    active: False
    model: tax_credit.models:TargetBonusAssoc
    target: county
    bonus: distressed
    assoc_strategy: overlap
    db_field_unique:
    - target_geography
    - bonus_geography
    db_field_update:
    - target_geography_type
    - bonus_geography_type
  county_to_energy:
    active: False
    model: tax_credit.models:TargetBonusAssoc
    target: county
    bonus: energy
    assoc_strategy: fips_county
    db_field_unique:
    - target_geography
    - bonus_geography
    db_field_update:
    - target_geography_type
    - bonus_geography_type
  county_to_j40:
    active: False
    model: tax_credit.models:TargetBonusAssoc
    target: county
    bonus: justice40
    assoc_strategy: fips_county
    db_field_unique:
    - target_geography
    - bonus_geography
    db_field_update:
    - target_geography_type
    - bonus_geography_type
  county_to_low_income:
    active: False
    model: tax_credit.models:TargetBonusAssoc
    target: county
    bonus: low_income
    assoc_strategy: fips_county
    db_field_unique:
    - target_geography
    - bonus_geography
    db_field_update:
    - target_geography_type
    - bonus_geography_type

  municipal_utility_to_distressed:
    active: False
    model: tax_credit.models:TargetBonusAssoc
    target: municipal utility
    bonus: distressed
    assoc_strategy: overlap
    db_field_unique:
    - target_geography
    - bonus_geography
    db_field_update:
    - target_geography_type
    - bonus_geography_type
  municipal_utility_to_energy:
    active: False
    model: tax_credit.models:TargetBonusAssoc
    target: municipal utility
    bonus: energy
    assoc_strategy: overlap
    db_field_unique:
    - target_geography
    - bonus_geography
    db_field_update:
    - target_geography_type
    - bonus_geography_type
  municipal_utility_to_j40:
    active: False
    model: tax_credit.models:TargetBonusAssoc
    target: municipal utility
    bonus: justice40
    assoc_strategy: overlap
    db_field_unique:
    - target_geography
    - bonus_geography
    db_field_update:
    - target_geography_type
    - bonus_geography_type
  municipal_utility_to_low_income:
    active: False
    model: tax_credit.models:TargetBonusAssoc
    target: municipal utility
    bonus: low_income
    assoc_strategy: overlap
    db_field_unique:
    - target_geography
    - bonus_geography
    db_field_update:
    - target_geography_type
    - bonus_geography_type

  municipality_to_distressed:
    active: False
    model: tax_credit.models:TargetBonusAssoc
    target: municipality
    bonus: distressed
    assoc_strategy: overlap
    db_field_unique:
    - target_geography
    - bonus_geography
    db_field_update:
    - target_geography_type
    - bonus_geography_type
  municipality_to_energy:
    active: False
    model: tax_credit.models:TargetBonusAssoc
    target: municipality
    bonus: energy
    assoc_strategy: fips_county
    db_field_unique:
    - target_geography
    - bonus_geography
    db_field_update:
    - target_geography_type
    - bonus_geography_type
  municipality_to_j40:
    active: False
    model: tax_credit.models:TargetBonusAssoc
    target: municipality
    bonus: justice40
    assoc_strategy: fips_county
    db_field_unique:
    - target_geography
    - bonus_geography
    db_field_update:
    - target_geography_type
    - bonus_geography_type
  municipality_to_low_income:
    active: False
    model: tax_credit.models:TargetBonusAssoc
    target: municipality
    bonus: low_income
    assoc_strategy: fips_county
    db_field_unique:
    - target_geography
    - bonus_geography
    db_field_update:
    - target_geography_type
    - bonus_geography_type

  rural_cooperative_to_distressed:
    active: True
    model: tax_credit.models:TargetBonusAssoc
    target: rural cooperative
    bonus: distressed
    assoc_strategy: overlap
    db_field_unique:
    - target_geography
    - bonus_geography
    db_field_update:
    - target_geography_type
    - bonus_geography_type
  rural_cooperative_to_energy:
    active: True
    model: tax_credit.models:TargetBonusAssoc
    target: rural cooperative
    bonus: energy
    assoc_strategy: overlap
    db_field_unique:
    - target_geography
    - bonus_geography
    db_field_update:
    - target_geography_type
    - bonus_geography_type
  rural_cooperative_to_j40:
    active: True
    model: tax_credit.models:TargetBonusAssoc
    target: rural cooperative
    bonus: justice40
    assoc_strategy: overlap
    db_field_unique:
    - target_geography
    - bonus_geography
    db_field_update:
    - target_geography_type
    - bonus_geography_type
  rural_cooperative_to_low_income:
    active: True
    model: tax_credit.models:TargetBonusAssoc
    target: rural cooperative
    bonus: low_income
    assoc_strategy: overlap
    db_field_unique:
    - target_geography
    - bonus_geography
    db_field_update:
    - target_geography_type
    - bonus_geography_type
