hydra:
  run:
    dir: .

paths:
  wd: "data"
  #Paths for the utility cleanup script
  utilities:
    util_shape_file_path: "${paths.wd}/utility shape file/Electric_Retail_Service_Territories.shp"
    util_clean_path: "${paths.wd}/coops_utilities/util_clean/util_clean.shp"
    rural_coops_path: "${paths.wd}/coops_utilities/rural_coops/rural_coops.shp"
    municipal_utils_path: "${paths.wd}/coops_utilities/municipal_utils/municipal_utils.shp"

  #Paths for the J40 clean up script
  j40: 
    j40_shp_path: "${paths.wd}/justice40 shapefile/usa/usa.shp"
    j40_clean_path : "${paths.wd}/communities/justice40/justice40.shp"

  #Paths for the energy communities cleanup script
  energy:
    coal_shp_path: "${paths.wd}/ira_data_coalclosure_energycomm_20231/IRA_Coal_Closure_Energy_Comm_SHP/Coal_Closure_Energy_Communities_shp/Coal_Closure_Energy_Communities.shp"
    coal_clean_path: "${paths.wd}/communities/energy_coal/coal_closure.shp"
    ffe_shp_path: "${paths.wd}/ira_data_msanmsa_ffe_20231/MSA_NMSA_FFE_SHP/MSA_NMSA_FFE_SHP.shp"
    ffe_clean_path: "${paths.wd}/communities/energy_ffe/ffe.shp"
    #energy_path: "${paths.wd}/communities/energy/energy.shp"

  #Paths for the low income communities cleanup script
  low_income:
    lic_path: "${paths.wd}/Low Income Communities"
    pov_dir: "${paths.low_income.lic_path}/poverty/R13409161_SL140.csv" #Poverty
    pov_save_path: "${paths.low_income.lic_path}/poverty/poverty_clean.csv"
    tract_inc_dir: "${paths.low_income.lic_path}/income/R13409069_SL140.csv" #Income Tract Level csv
    tract_inc_save_path: "${paths.low_income.lic_path}/income/income_clean.csv"
    st_inc_dir: "${paths.low_income.lic_path}/income/R13411548_SL040.csv" #Income State Level csv
    st_inc_save_path: "${paths.low_income.lic_path}/income/income_state_clean.csv"
    st_tract_merged_save_path: "${paths.low_income.lic_path}/income/income_tract_st_merged.csv" #Income State and Tract Merged
    msa_inc_dir: "${paths.low_income.lic_path}/income/R13411591_SL320.csv" #Income MSA Level csv
    msa_save_path: "${paths.low_income.lic_path}/income/income_msa_clean.csv"
    msa_shape_path: "${paths.low_income.lic_path}/income/2020_msa_shp/tl_2020_us_cbsa.shp" #MSA Shapefile
    msa_clean_save_path: "${paths.low_income.lic_path}/income/msa_clean_shp/msa_clean.shp" 
    msa_inc_shp_save_path: "${paths.low_income.lic_path}/income/msa_income_shp/msa_income_shp.shp" #MSA Income Merged
    tract_shp_path: "${paths.low_income.lic_path}/merged_tracts_2020/merged_tracts_2020.shp" #Tract Shapefile
    low_inc_clean_path: "${paths.wd}/communities/low_income/low_income_tracts.shp" #Final Shapefile

  #Paths for the County and State borders cleanup script
  boundaries:
    ct_path: "${paths.wd}/county_tract/tl_2020_us_county.shp" 
    st_path: "${paths.wd}/state_tract/tl_2020_us_state.shp" 
    ct_clean_path: "${paths.wd}/boundaries/county_clean/county_clean.shp" 
    st_clean_path: "${paths.wd}/boundaries/state_clean/state_clean.shp" 
    state_fips_path: "${paths.wd}/state_fips.csv" #State FIPS dataset to be used for both Utils and Borders

  #Paths for the overlay script
  overlays:
    j40_overlay_path: "${paths.wd}/overlays/j40_overlays/j40_overlays.shp" 
    coal_overlay_path: "${paths.wd}/overlays/coal_overlays/coal_overlays.shp" 
    ffe_overlay_path: "${paths.wd}/overlays/ffe_overlays/ffe_overlays.shp" 
    #energy_overlay_path: "${paths.wd}/overlays/energy_overlays/energy_overlays.shp" #Energy Overlays dataset save path for future if overlay is successful
    low_income_overlay_path: "${paths.wd}/overlays/low_income_overlays/low_income_overlays.shp" 

  #Path to save the final result maps
  maps:
    output_html_path: "${paths.wd}/results/IL_Overlay_Map.html" #Output html file path

  #Paths for webscraper file
  scraper:
    base_url_2021: "'https://www2.census.gov/geo/tiger/TIGER2021/TRACT/"
    base_url_2020: "'https://www2.census.gov/geo/tiger/TIGER2020/TRACT/"
    all_tracts_zip_save_path: "${paths.wd}/all_tracts_2020" 
    merged_tracts_path: "${paths.wd}/merged_tracts_2020/merged_tracts_2020.shp"

constants:
  #Constants for the coop_util_cleanup script
  utilities:
    drop_cols: ["OBJECTID", "SOURCE", "SOURCEDATE", "VAL_METHOD", "VAL_DATE", "WEBSITE", "CNTRL_AREA", "PLAN_AREA", "HOLDING_CO", "SUMMR_PEAK",'WINTR_PEAK','SUMMER_CAP', 'WINTER_CAP', 'NET_GEN', 'PURCHASED', 'NET_EX']
    rename_cols: {'STATE': 'ST_Code'}
    state_cols: ["Abbreviation", "State"]
    state_rename_col : {"Abbreviation":"ST_Code"}
    area: "area"
    st_code: "ST_Code"
    geo: "geometry"
    filter_col: "TYPE" 
    filters: ["MUNICIPAL", "POLITICAL SUBDIVISION","COOPERATIVE"]
    filters_new: ["Municipal/Public Utility", "Rural Co-Op"]
    new_col: "Type"

  #Constants for the justice40_cleanup script
  j40:
    cols_to_keep: ['GEOID10','SF', 'CF','TPF','UF_PFS','SN_C','SN_T','HRS_ET','LHE','FPL200S','UI_EXP','THRHLD','geometry']
    rename_cols: {'GEOID10': 'TractID', 'SF': 'State', 'CF': 'County', 'TPF': 'Tot_Pop', 'UF_PFS': 'Unemp_Per', 'SN_C': 'Disadv?', 'SN_T': 'Disad_Tri?', 'HRS_ET': 'Underinves', 'LHE': 'Low_HS_Edu', 'FPL200S': 'Low_Income', 'UI_EXP': 'UI_EXP', 'THRHLD': 'THRHLD', 'geometry': 'geometry'}
    filter_cols: ['Disadv?', 'geometry']
    area: 'area_j40'
    geo: 'geometry'
    new_col: 'Type'
    new_col_val: 'J40'

  #Constants for the energy_communities_clean script
  energy:
    coal_drop_cols : ['objectid', 'affgeoid_t', 'fipstate_2', 'fipcounty_', 'geoid_coun','fiptract_2','censustrac','date_last_','dataset_ve']
    coal_rename_cols: {'geoid_trac':'TractID', 'state_name':'State','county_nam':'County','mine_closu':'mine_clos','generator_':'gen_clos','adjacent_t':'adj_clos'}
    coal_area: 'area_coal'
    geo: 'geometry'
    coal_subtype: 'Energy - Coal Closure'
    ffe_drop_cols: ['ObjectID','fipstate_2','fipscty_20','geoid_cty_','MSA_area_I','Date_Last_','Dataset_ve']
    ffe_rename_cols: {'AFFGEOID_C':'TractIDcty','state_name':'State','county_nam':'County','FFE_qual_s':'is_FFE','MSA_NMSA_L':'M_NMSA_loc','Shape_Leng':'Leng_Cty','Shape_Area':'Area_Cty'}        
    ffe_area: 'area_ffe'
    ffe_subtype: 'Energy - Fossil Fuel Employment'
    new_cols: ['Type', 'Subtype']
    type_val: 'Energy Community'

  #Constants for the low_income_cleanup script
  low_income:
    state: 'state'
    geo: 'geometry'
    pov_cols_to_keep: ['Geo_STUSAB','Geo_GEOID','Geo_QName','Geo_FIPS','Geo_AREALAND','Geo_AREAWATR','ACS20_5yr_B17020001','ACS20_5yr_B17020002']
    pov_renamed_cols: {'Geo_STUSAB': 'state', 'Geo_GEOID': 'geo_id', 'Geo_QName': 'tract_name', 'Geo_FIPS': 'tractId', 'Geo_AREALAND': 'area_land', 'Geo_AREAWATR': 'area_water', 'ACS20_5yr_B17020001': 'total_pop', 'ACS20_5yr_B17020002': 'pov_pop'}
    pov_perc: 'pov_perc'
    pov_pop: 'pov_pop'
    pov_tot_pop: 'total_pop'
    li_tract_csv_cols_to_keep: ['Geo_STUSAB','Geo_GEOID','Geo_QName', 'Geo_FIPS', 'Geo_AREALAND', 'Geo_AREAWATR','ACS20_5yr_B19113001']
    li_tract_csv_renamed_cols: {'Geo_STUSAB': 'state', 'Geo_GEOID': 'geoId', 'Geo_QName': 'tractName', 'Geo_FIPS': 'tractId', 'Geo_AREALAND': 'area_land', 'Geo_AREAWATR': 'area_water', 'ACS20_5yr_B19113001': 'med_inc'}
    st_csv_cols_to_keep: ['Geo_STUSAB','Geo_GEOID','Geo_QName','Geo_AREALAND', 'Geo_AREAWATR','ACS20_5yr_B19113001']
    st_csv_renamed_cols: {'Geo_STUSAB': 'state', 'Geo_GEOID': 'geoId', 'Geo_QName': 'st_name', 'Geo_AREALAND': 'area_land', 'Geo_AREAWATR': 'area_water', 'ACS20_5yr_B19113001': 'st_med_inc'}
    msa_csv_cols_to_keep: ['Geo_STUSAB','Geo_CBSA','Geo_GEOID','Geo_QName','Geo_FIPS','Geo_AREALAND',  'Geo_AREAWATR','ACS20_5yr_B19113001']
    msa_csv_renamed_cols: {'Geo_STUSAB': 'state', 'Geo_CBSA': 'cbsaId', 'Geo_GEOID': 'geoId', 'Geo_QName': 'msaName', 'Geo_FIPS': 'msaTractId', 'Geo_AREALAND': 'area_land', 'Geo_AREAWATR': 'area_water', 'ACS20_5yr_B19113001': 'msa_medInc'}
    msa_shp_cols_to_keep: ['GEOID','NAMELSAD','LSAD','ALAND','AWATER','INTPTLAT','INTPTLON','geometry']
    msa_shp_renamed_cols: {'GEOID': 'cbsaId', 'NAMELSAD': 'msaName', 'LSAD': 'lsad', 'ALAND': 'area_land', 'AWATER': 'area_water', 'INTPTLAT': 'lat', 'INTPTLON': 'lon', 'geometry': 'geometry'}
    msa_shp_cbsaId : 'cbsaId'
    msa_shp_merge_cols: ['cbsaId','lsad','lat','lon','geometry']
    merge_all:
      inc_merged_cols: ['state','geoId_x','tractName','tractId','med_inc','st_med_inc'] 
      inc_merged_cols_renamed: {'geoId_x': 'geoId'}
      tract_shp_cols: ['stateFP','tract_id','tract_name','area_land','area_water','lat','lon','geometry']
      leftid: 'tractId'
      rightid: 'tract_id'
      pov_cols: ['tractId','total_pop','pov_pop','pov_perc']
      pov_drop_cols: ['tract_id', 'tract_name']
      pov_col_order: ['stateFP','state','geoId','tractId','tractName','med_inc','st_med_inc','total_pop','pov_pop','pov_perc','area_land','area_water','lat','lon','geometry']
      msa_inc_shp_cols_to_keep: ['state','cbsaId','geoId','msaName','msaTractId','lsad','msa_medInc','geometry']
      msa_inc_shp_renamed_cols: {'state': 'state_msa', 'cbsaId': 'cbsaId', 'geoId': 'geoIdMsa', 'msaName': 'msaName', 'msaTractId': 'msaTractId', 'lsad': 'lsad', 'msa_medInc': 'msa_medInc', 'geometry': 'geometry'}
      final_merged_col_order: ['stateFP','state','geoId','tractId','tractName','cbsaId','geoIdMsa','msaName','msaTractId','lsad','med_inc','st_med_inc','msa_medInc','total_pop','pov_pop','pov_perc','area_land','area_water','lat','lon','geometry']
      area: 'area_li'
    li_conds:
      li_col: 'Type'
      pov_perc: 'pov_perc'
      med_inc: 'med_inc'
      st_med_inc: 'st_med_inc'
      lsad: 'lsad'
      m1: 'M1'
      msa_medInc: 'msa_medInc'
  
  #Constants for county_st_borders cleanup script
  ct_st_borders:
    statefp: 'STATEFP'
    cols_read_csv: ['St_FIPS', 'State'] 
    cols_rename_csv: {'St_FIPS':'STATEFP'}
    cols_drop_cty: ['COUNTYNS','GEOID','NAME','LSAD','CLASSFP','MTFCC','CSAFP','CBSAFP','METDIVFP','FUNCSTAT']
    ct_rename_cols: {'NAMELSAD':'County'}
    st_drop_cols: ['REGION', 'DIVISION',  'STATENS', 'GEOID','LSAD','MTFCC','FUNCSTAT']
    st_rename_cols: {'NAME':'State'}
      


