name: Deploy to Google Artifact Registry

on:
  # workflow_dispatch:
  #   env:
  #     # Setting an environment variable with the value of a configuration variable
  #     env_var: ${{ vars.ENV_CONTEXT_VAR }}
  push:
    branches:
      # TODO: change this eventually
      - cloud-csv-reader

jobs:
  build-and-push:
    environment: "Climate Cabinet"
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions. Used for OIDC connection with GitHub
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      # Needs to be run before "auth" action
      - uses: "actions/checkout@v3"

      # Use OIDC authentication to get an access token from GitHub
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          # TODO: put these settings in config
          workload_identity_provider: "projects/586636400432/locations/global/workloadIdentityPools/artifact-registry/providers/github"
          # service_account: "artifact-registry@climate-cabinet-398217.iam.gserviceaccount.com"
          service_account: ${{ vars.ARTIFACT_SERVICE_ACCOUNT }}
          token_format: "access_token"

      # Login with Docker action using the token from the Google Cloud auth step
      # - uses: "docker/login-action@v1"
      - uses: "docker/login-action@v3"
        with:
          registry: "us-central1-docker.pkg.dev" # TODO: this should maybe be in config
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"

      - id: "docker-push-tagged"
        name: "Tag Docker image and push to Google Artifact Registry"
        # uses: "docker/build-push-action@v2"
        uses: "docker/build-push-action@v5"
        with:
          push: true
          # TODO: this stuff should probably be in a config file also
          context: ./pipeline
          file: ./pipeline/Dockerfile
          tags: us-central1-docker.pkg.dev/climate-cabinet-398217/ira-pipeline/climate-cabinet-pipeline:latest
