name: Deploy to Google Artifact Registry

on:
  push:
    branches:
      - artifact-registry

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authenticate with Google Cloud
        uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: climate-cabinet-398217
          export_default_credentials: true

      - name: Build and push Docker image to Artifact Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./pipeline/Dockerfile
          # TODO: should we move this stuff to a config file?
          tags: us-central1-docker.pkg.dev/climate-cabinet-398217/ira-pipeline/climate-cabinet-pipeline:latest
