name: Deploy to Google Artifact Registry

on:
  push:
    branches:
      # TODO: change this eventually
      - artifact-registry

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v3"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/586636400432/locations/global/workloadIdentityPools/artifact-registry/providers/github"
          service_account: "artifact-registry@climate-cabinet-398217.iam.gserviceaccount.com"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image to Artifact Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./pipeline/Dockerfile
          # TODO: should we move this stuff to a config file?
          tags: us-central1-docker.pkg.dev/climate-cabinet-398217/ira-pipeline/climate-cabinet-pipeline:latest
